# Generated by Django 5.2.5 on 2025-09-04 12:51

import django.contrib.postgres.fields
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0002_project_projecttranslation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("position", models.CharField(max_length=128, verbose_name="Position")),
                ("start", models.DateField(verbose_name="Start")),
                ("end", models.DateField(blank=True, null=True, verbose_name="End")),
                ("company", models.CharField(max_length=128, verbose_name="Company")),
                (
                    "technologies",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128, verbose_name="Technologies"),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experiences",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ExperienceTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("location", models.CharField(max_length=128, verbose_name="Location")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Description")),
                (
                    "achievements",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=512, verbose_name="Achievements"),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="work.experience",
                    ),
                ),
            ],
            options={
                "verbose_name": "Experience Translation",
                "db_table": "work_experience_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
