# Generated by Django 5.2.5 on 2025-09-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0003_experience_experiencetranslation"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.URLField(blank=True, null=True, verbose_name="Image URL"),
        ),
        migrations.AddField(
            model_name="skill",
            name="image",
            field=models.URLField(blank=True, null=True, verbose_name="Image URL"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="level",
            field=models.CharField(
                choices=[
                    ("3+ years of experience", "3+ years of experience"),
                    ("5+ years of experience", "5+ years of experience"),
                    ("10+ years of experience", "10+ years of experience"),
                ],
                default="3+ years of experience",
            ),
        ),
    ]
