# Generated by Django 5.2.5 on 2025-09-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0004_project_image_skill_image_alter_skill_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="image",
        ),
        migrations.AddField(
            model_name="skill",
            name="icon",
            field=models.CharField(
                choices=[("Code", "Code"), ("Database", "Database"), ("Brain", "Brain"), ("Server", "Server")],
                default="Code",
                max_length=8,
            ),
        ),
    ]
