# Generated by Django 5.2.5 on 2025-09-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vex", "0003_document_alter_conversation_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="is_active",
        ),
        migrations.AddField(
            model_name="document",
            name="injected",
            field=models.BooleanField(default=False, verbose_name="Injected"),
        ),
    ]
