# Generated by Django 5.2.5 on 2025-09-16 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vex", "0004_remove_document_is_active_document_injected"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="title",
        ),
    ]
