# Generated by Django 5.2.5 on 2026-09-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0006_alter_skill_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="level",
            field=models.CharField(
                choices=[
                    ("3+ years of experience", "3+ years of experience"),
                    ("5+ years of experience", "5+ years of experience"),
                    ("10+ years of experience", "10+ years of experience"),
                    ("Since launch", "Since launch"),
                ],
                default="3+ years of experience",
            ),
        ),
    ]
