# Generated by Django 5.2.5 on 2026-10-08 04:25

import django.contrib.postgres.fields
from django.db import migrations, models
from django.db.models import OuterRef, Subquery

import utils.fields


def copy_position_to_role(apps, schema_editor):  # pylint: disable=unused-argument
    """Each role's current title, in every language it has, as the start of its translated role."""
    Experience = apps.get_model("work", "Experience")
    ExperienceTranslation = apps.get_model("work", "ExperienceTranslation")
    position = Experience.objects.filter(pk=OuterRef("master_id")).values("position")[:1]
    ExperienceTranslation.objects.filter(role="").update(role=Subquery(position))


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0007_alter_skill_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="tools",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128),
                blank=True,
                help_text="Programming tools used in the role, e.g. Copilot, Claude Code.",
                null=True,
                size=None,
                verbose_name="Tools",
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="topics",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128),
                blank=True,
                help_text="Subjects taught, for a teaching or training role.",
                null=True,
                size=None,
                verbose_name="Topics",
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="visible",
            field=models.BooleanField(
                db_default=True,
                default=True,
                help_text="Shown on the site and to Vex. Uncheck to keep the role without showing it.",
                verbose_name="Visible",
            ),
        ),
        migrations.AddField(
            model_name="experiencetranslation",
            name="contributions",
            field=utils.fields.LinesArrayField(
                base_field=models.CharField(max_length=512),
                blank=True,
                null=True,
                size=None,
                verbose_name="Contributions",
            ),
        ),
        migrations.AddField(
            model_name="experiencetranslation",
            name="product",
            field=models.TextField(blank=True, null=True, verbose_name="Product"),
        ),
        migrations.AddField(
            model_name="experiencetranslation",
            name="responsibilities",
            field=models.TextField(blank=True, null=True, verbose_name="Responsibilities"),
        ),
        migrations.AddField(
            model_name="experiencetranslation",
            name="results",
            field=utils.fields.LinesArrayField(
                base_field=models.CharField(max_length=512),
                blank=True,
                null=True,
                size=None,
                verbose_name="Results",
            ),
        ),
        migrations.AddField(
            model_name="experiencetranslation",
            name="role",
            field=models.CharField(
                blank=True,
                db_default="",
                help_text="The role's title in this language; it replaces Position, still shown by the current site.",
                max_length=128,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="experiencetranslation",
            name="achievements",
            field=utils.fields.LinesArrayField(
                base_field=models.CharField(max_length=512, verbose_name="Achievements"),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.RunPython(copy_position_to_role, migrations.RunPython.noop),
    ]
