# Generated by Django 5.2.5 on 2026-10-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0009_skill_since"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiencetranslation",
            name="vex_question",
            field=models.CharField(
                blank=True,
                db_default="",
                help_text="What the Ask Vex prompt offers to ask about it. Leave empty for a general question.",
                max_length=255,
                verbose_name="Vex question",
            ),
        ),
        migrations.AddField(
            model_name="projecttranslation",
            name="vex_question",
            field=models.CharField(
                blank=True,
                db_default="",
                help_text="What the Ask Vex prompt offers to ask about it. Leave empty for a general question.",
                max_length=255,
                verbose_name="Vex question",
            ),
        ),
    ]
