# Generated by Django 5.2.5 on 2025-09-05 11:06

import django.contrib.postgres.fields
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("start", models.DateField(verbose_name="Start")),
                ("end", models.DateField(blank=True, null=True, verbose_name="End")),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SchoolTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("study", models.CharField(max_length=128)),
                ("university", models.CharField(max_length=128)),
                ("research", models.TextField()),
                ("advisor", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "areas",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128), blank=True, null=True, size=None
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="university.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "School Translation",
                "db_table": "university_school_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
