# Generated by Django 5.2.5 on 2025-11-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0005_schooltranslation_degree"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schooltranslation",
            name="degree",
        ),
        migrations.AddField(
            model_name="school",
            name="degree",
            field=models.CharField(
                choices=[
                    ("Bachelor Degree", "Bachelor Degree"),
                    ("Master Degree", "Master Degree"),
                    ("Doctorate Degree", "Doctorate Degree"),
                ],
                default="Bachelor Degree",
                max_length=64,
                verbose_name="Degree",
            ),
        ),
    ]
