# Generated by Django 5.2.5 on 2025-09-05 11:54

import django.contrib.postgres.fields
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("title", models.CharField(max_length=256, verbose_name="Title")),
                ("journal", models.CharField(max_length=256, verbose_name="Journal")),
                ("link", models.URLField(blank=True, null=True, verbose_name="Link")),
                ("year", models.PositiveSmallIntegerField(verbose_name="Year")),
            ],
            options={
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterField(
            model_name="schooltranslation",
            name="advisor",
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name="Advisor"),
        ),
        migrations.AlterField(
            model_name="schooltranslation",
            name="areas",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128, verbose_name="Areas"), blank=True, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="schooltranslation",
            name="research",
            field=models.TextField(verbose_name="Research"),
        ),
        migrations.AlterField(
            model_name="schooltranslation",
            name="study",
            field=models.CharField(max_length=128, verbose_name="Study"),
        ),
        migrations.AlterField(
            model_name="schooltranslation",
            name="university",
            field=models.CharField(max_length=128, verbose_name="University"),
        ),
        migrations.CreateModel(
            name="PublicationTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("summary", models.TextField(verbose_name="Summary")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="university.publication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publication Translation",
                "db_table": "university_publication_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
