# Generated by Django 5.2.5 on 2025-11-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0003_testimonial_testimonialtranslation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="title",
        ),
        migrations.AddField(
            model_name="publicationtranslation",
            name="title",
            field=models.CharField(default="Default Title of Publication", max_length=256, verbose_name="Title"),
            preserve_default=False,
        ),
    ]
