# Generated by Django 5.2.5 on 2025-11-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0006_remove_schooltranslation_degree_school_degree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="degree",
            field=models.CharField(
                choices=[
                    ("Bachelor's", "Bachelor's"),
                    ("Master's", "Master's"),
                    ("Doctoral Studies", "Doctoral Studies"),
                ],
                default="Bachelor's",
                max_length=64,
                verbose_name="Degree",
            ),
        ),
    ]
