# Generated by Django 5.2.5 on 2025-09-13 11:33

from django.db import migrations


def create_pgvector_extension(apps, schema_editor) -> None:
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            DO $$
            BEGIN
                CREATE EXTENSION IF NOT EXISTS vector;
            EXCEPTION WHEN undefined_file THEN
                RAISE NOTICE 'pgvector extension not installed on server; skipping';
            END;
            $$;
            """
        )


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.RunPython(create_pgvector_extension, reverse_code=migrations.RunPython.noop),
    ]
