# Generated by Django 5.2.5 on 2025-09-13 11:33

from django.db import migrations


def create_pgvector_extension(apps, schema_editor) -> None:
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT 1 FROM pg_available_extensions WHERE name = 'vector'")
        if not cursor.fetchone():
            return
        cursor.execute("CREATE EXTENSION IF NOT EXISTS vector;")


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.RunPython(create_pgvector_extension, reverse_code=migrations.RunPython.noop),
    ]
