# Generated by Django 5.2.5 on 2025-09-13 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vex", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("session", models.CharField(db_index=True, max_length=64, verbose_name="Session Key")),
                ("title", models.CharField(blank=True, max_length=256, null=True, verbose_name="Title")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "user"), ("assistant", "assistant"), ("system", "system")],
                        max_length=16,
                        verbose_name="Role",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="vex.conversation"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
