# Generated by Django 5.2.5 on 2025-09-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vex", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("title", models.CharField(max_length=256, verbose_name="Title")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Description")),
                ("file", models.FileField(blank=True, null=True, upload_to="vex_docs/", verbose_name="File")),
                ("url", models.URLField(blank=True, null=True, verbose_name="Source URL")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.AlterModelOptions(
            name="conversation",
            options={"verbose_name": "Conversation", "verbose_name_plural": "Conversations"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Message", "verbose_name_plural": "Messages"},
        ),
    ]
