# Generated by Django 5.2.5 on 2025-09-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vex", "0005_remove_conversation_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("pl", "Polski")], default="en", max_length=2, verbose_name="Language"
            ),
        ),
    ]
